### ISSUE TITLE
GPU support? 

### ISSUE THREAD

**Issue by yeoneee** [sid-sundrani/ppo_lightning#1]
Hi, can I run this PPO code with gpu support?

like just gpus option in PL ... e.g) Trainer = Trainer(gpus=-1)
Thanks in advance!

**Comment by sidhantls** [comment]
Yes, it does support GPUs. Just doing `trainer = Trainer(gpus=-1)` should work 

However, training with GPU is slower than CPU here because of the overhead of moving each sample during trajectory collection to GPU. If you are using a deep network for the agent, instead of the default MLP, it would make more sense to use the GPU
